# Generated by Django 2.0.4 on 2018-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('category', models.CharField(choices=[('冷菜类', 'cold'), ('汤煲类', 'soup'), ('荤菜小炒', 'meat'), ('素菜小炒', 'vege'), ('米饭', 'rice')], default='米饭', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_price', models.FloatField(max_length=4)),
                ('m_id', models.ForeignKey(on_delete=True, to='Order.Menu')),
            ],
        ),
    ]
