# Generated by Django 2.0.4 on 2018-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('cold', '冷菜类'), ('soup', '汤煲类'), ('meat', '荤菜小炒'), ('vege', '素菜小炒'), ('rice', '米饭')], default='cold', max_length=20, null=True),
        ),
    ]
