# Generated by Django 2.0.4 on 2018-06-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20180607_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('cold', '冷菜类'), ('soup', '汤煲类'), ('meat', '荤菜小炒'), ('vege', '素菜小炒'), ('rice', '主食')], default='cold', max_length=20, null=True),
        ),
    ]
