# Generated by Django 2.0.4 on 2018-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20180619_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='count',
            field=models.IntegerField(default=0, max_length=99),
        ),
    ]
