# Generated by Django 2.0.4 on 2018-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='o_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='o_id',
            field=models.ManyToManyField(to='Order.Order'),
        ),
    ]
